### ISSUE TITLE
How fast is accessing DOM elements from .net

### ISSUE THREAD

**Issue by vibeeshan025** [SteveSandersonMS/BlazorElectronExperiment.Sample#3]
We know as of now most browsers (Firefox is better) are slow in accessing DOM elements from blazor using invoke(). Is there any mechanisms to improve this using a custom browser like electron.

**Comment by SteveSandersonMS** [comment]
Not aware of anything about Electron that would make it faster. However browsers themselves are getting much faster at this, especially Firefox (https://hacks.mozilla.org/2018/10/calls-between-javascript-and-webassembly-are-finally-fast-%F0%9F%8E%89/).
